version: '3.9'

services:
  api:
    container_name: med_service
    image: med/api:0.0.1
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

  pgdb:
    container_name: med_db
    image: mdillon/postgis:11-alpine
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
